#' @title TFScoring - TF Scoring for evaluation
#' @param filepath Directory path to read output network from GSO algorithms.
#' @param algorithm Three group sparse optimization algorithms: Soft, Half and Hard.
#' @param TFlist list of candidate TFs.
#' @param TFtrue Gold standard TFs.
#' @param sparSeq Sequence of group sparsity level.
#' @author Jing Qin <qinj29@mail.sysu.edu.cn>
#'
#' Xinlin Hu <thompson-xinlin.hu@connect.polyu.hk>
#'
#' @details The score matrix is generated by all networks with different sparsity.
#' The TFScoring result consider the first 20 TFs with largest score.
#'
#' @import stringr
#' @import data.table
#' @importFrom stats na.omit
#' @importFrom utils write.csv
#' @export TFScoring
#' @examples
#' ntf <- 30
#' ngene <- 300
#' nsample <- 20
#' A <- matrix(rnorm(ntf*nsample), nrow = nsample, ncol = ntf)
#' B <- matrix(rnorm(ngene*nsample), nrow = nsample, ncol = ngene)
#' InitialX <- matrix(rnorm(ntf*ngene), nrow = ngene, ncol = ntf)
#' sparSeq <- c(1:10,seq(10,20,2))
#' algorithm <- 'Hard'
#' TFlist <- paste0('G',1:ntf)
#' TFtrue <- paste0('G',1:10)
#' resGSO <- demo_GSO(A, B, InitialX, algorithm, sparSeq)
#' res <- TFScoring('Output/',algorithm = algorithm,TFlist = TFlist,TFtrue = TFtrue,sparSeq = sparSeq)
TFScoring <- function(filepath, algorithm, TFlist, TFtrue, sparSeq){
  Score <- matrix(0, length(TFlist), length(sparSeq))
  rownames(Score) <- TFlist
  # Calculate each Score in different sparsity
  for(nr in 1:length(sparSeq)){
    s <- sparSeq[nr]
    # txtpath
    txtpath <- str_c('x', algorithm, '.txt')
    path <- str_c(filepath, '/s', s, '/', txtpath)
    A <- as.matrix(fread(path))
    ind <- which(A[1, ]!=0)
    Score[ind, nr] <- 1/s
    ind <- which(apply(A,2,norm,'2')!=0)
    Score[ind, nr] <- 1/s
  }
  # Maximum Score
  TFScore <- apply(Score, 1, max)
  TFScore <- TFScore[-TFScore!=0]
  TFScore <- sort(TFScore, decreasing = TRUE)[1:20] # Choose Top 20 TFs
  IND <- na.omit(match(TFtrue, names(TFScore)))
  rankTFSc <- 21 - order(TFScore, decreasing = TRUE)
  if(length(IND) == 0){
    rankTFSc[1:20] <- 0
  }else{
    rankTFSc[-IND] <- 0
  }
  outTFScore <- data.frame(TF = names(TFScore), rankScore = rankTFSc, TFScore = TFScore)
  rownames(outTFScore) <- c()
  write.csv(outTFScore, file = str_c('Output/', algorithm, '.tfscore.csv'))
  return(outTFScore)
}
